// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk0t0XLvc7g-3MH-QmDnQPwNKUfm7Z-2Q',
    appId: '1:790779060279:web:5cfda99119d72dcd80dfb2',
    messagingSenderId: '790779060279',
    projectId: 'flutter-maps-b859e',
    authDomain: 'flutter-maps-b859e.firebaseapp.com',
    storageBucket: 'flutter-maps-b859e.appspot.com',
    measurementId: 'G-PGZQPMW27J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvUJVCcccwzY64ltHEZ3pdJdbEU3wTz9Q',
    appId: '1:790779060279:android:6b1aa7fa7d5cb04880dfb2',
    messagingSenderId: '790779060279',
    projectId: 'flutter-maps-b859e',
    storageBucket: 'flutter-maps-b859e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJ5U7x5o-8o2ohUK5cuUMjnSSjXJGJ7-I',
    appId: '1:790779060279:ios:d5ece8de156b404280dfb2',
    messagingSenderId: '790779060279',
    projectId: 'flutter-maps-b859e',
    storageBucket: 'flutter-maps-b859e.appspot.com',
    iosClientId: '790779060279-8tghhsc028dlkmr5ihp40ehed1aj95e2.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterMaps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJ5U7x5o-8o2ohUK5cuUMjnSSjXJGJ7-I',
    appId: '1:790779060279:ios:d5ece8de156b404280dfb2',
    messagingSenderId: '790779060279',
    projectId: 'flutter-maps-b859e',
    storageBucket: 'flutter-maps-b859e.appspot.com',
    iosClientId: '790779060279-8tghhsc028dlkmr5ihp40ehed1aj95e2.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterMaps',
  );
}
